name: push go app
on: 
  push: 
    branches: [ "master" ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@master
    - name: setup go
      uses: actions/setup-go@v3     
      with: 
        go-version: 1.19
    - name: check go version
      run: go version
    - name: go mod init 
      run: go mod init github.com/thedevopsschool/user-service
    - name: go mod tidy
      run: go mod tidy 
    - name: go build
      run: go build -o user-service 
      
    #Build and Push image to dockerhub  
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: thedevopsschool/user-service
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    #Deploying to minikube(Kubernetes Cluster)
        
    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply deployment.yaml
        
      
      
